[theme]
# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = 'lightblue'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'lightpink'

# Color used for almost all text
textColor = 'black'



# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

[server]
port = 8501
enableStaticServing = true

[browser]
gatherUsageStats = false